DROP TABLE IF EXISTS sensor;
DROP TABLE IF EXISTS status;

CREATE TABLE sensor (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	dev_id TEXT UNIQUE NOT NULL,
	sensorname TEXT NOT NULL
);

CREATE TABLE status (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	sensor_id INTEGER NOT NULL,
	session_id INTEGER NOT NULL,
	received TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_tx DATETIME NOT NULL,
	temperature FLOAT NOT NULL,
	voltage FLOAT NOT NULL,
	FOREIGN KEY (sensor_id) REFERENCES sensor (id) ON DELETE CASCADE
    FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE
);

CREATE TABLE session (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_name TEXT UNIQUE NOT NULL,
    begin_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    type TEXT NOT NULL,
    color TEXT,
    sensor_id INTEGER NOT NULL,
    FOREIGN KEY (sensor_id) REFERENCES sensor (id) ON DELETE CASCADE
);
