DROP TABLE IF EXISTS sensor;
DROP TABLE IF EXISTS status;

CREATE TABLE sensor (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	dev_id TEXT UNIQUE NOT NULL,
	sensorname TEXT NOT NULL
);

CREATE TABLE status (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	sensor_id INTEGER NOT NULL,
	received TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_tx DATETIME NOT NULL,
	temperature FLOAT NOT NULL,
	voltage FLOAT NOT NULL,
	FOREIGN KEY (sensor_id) REFERENCES sensor (id) ON DELETE CASCADE
);
